#ifndef SH100_MEMORY_H_
#define SH100_MEMORY_H_

#include "sh100_controller.h"

#define MEMORY_MAGIC_WORD 0xACAB
#define MEMORY_MW_AMP_STATE_OFFSET 0
#define MEMORY_MW_MIDI_COMMANDS_OFFSET 2


#define MEMORY_FSW_MODE_OFFSET 7
#define MEMORY_AMP_STATE_OFFSET 8

#define MEMORY_USER_PRESETS_OFFSET 128

#endif /* SH100_MEMORY_H_ */